name: cmms
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  clipboard: ^0.1.3
  dio: ^4.0.4
  dotted_border: ^2.0.0+3
  excel: ^2.1.0
  file_picker: ^5.2.6
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^6.0.0
  flutter_share: ^2.0.0
  flutter_staggered_grid_view: ^0.6.0
  flutter_svg: ^1.0.3
  flutter_test:
    sdk: flutter
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  http: ^1.2.1
  image_picker: ^0.8.4+4
  internet_connection_checker: ^0.0.1+1
  intl: ^0.19.0
  loading_animation_widget: ^1.1.0+1
  loading_overlay_pro: ^2.1.1
  logger: ^1.0.0
  permission_handler: ^10.0.0
  scrollable_table_view: ^1.0.1
  fluttertoast: ^8.2.2
  share: ^2.0.4
  url_launcher: ^6.1.6
  multi_select_flutter: ^4.1.3
  dropdown_search: ^5.0.6
  flutter_dropzone: ^3.0.5
  http_parser: ^4.0.2
  rxdart: ^0.27.7
  filesize: ^2.0.1
  synchronized: ^3.0.1
  syncfusion_flutter_datepicker: ^27.1.53
  syncfusion_flutter_pdf: ^27.1.53
  syncfusion_flutter_charts: ^27.1.53
  syncfusion_flutter_calendar: ^27.1.53
  html_unescape: ^2.0.0
  data_table_2: ^2.4.2
  package_info_plus: ^4.2.0
  flutter_cache_manager: ^3.3.1
  path_provider: ^2.1.1
  universal_html: ^2.2.2
  google_fonts: ^4.0.4
  percent_indicator: ^4.2.3
  semicircle_indicator: ^1.1.1
  pie_chart: ^5.4.0
  csv: ^5.1.1
  calendar_date_picker2: ^1.1.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  multi_dropdown: ^3.0.1
  get: ^4.6.6

dev_dependencies:
  hive_generator:
  build_runner: ^2.3.3
  json_serializable: ^6.6.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/cmms_logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/files/
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 600
